spring.application.name=frontend

# Backend API Configuration (group-based, comment out unused groups)
backend.api.iti.base-url=yout base url for iti API
backend.api.iti.path=/api/iti
backend.api.reports.base-url=http://localhost:5050/itiapreports
backend.api.reports.path=/api/reports
backend.api.iti-application.base-url=http://localhost:5050
backend.api.iti-application.path=/api/reports
backend.api.districts.base-url=your base url for districts API
backend.api.districts.path=/api/districts
backend.api.designations.base-url=yout base url for designations API
backend.api.designations.path=/api/designations
backend.api.shift-unit.base-url=your base url for shift unit API
backend.api.shift-unit.path=/api/shift-unit-permitted

# Frontend Server
server.port=5051

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/

spring.mvc.view.suffix=.jsp

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.server.frontend=DEBUG